### ISSUE TITLE
Detection of missing mandatory annotations

### ISSUE THREAD

**Issue by vtoure** [MI2CAST/causalBuilder#3]
A pop up warning message should appear when mandatory annotations are empty.
An option to proceed can be provided.

**Comment by stcruy** [comment]
Implemented :) It now always
- converts as much as is available,
- shows an alert if something mandatory was missing,
- and then proceeds to downloading.

**Comment by stcruy** [comment]
Update: it will only be shown on the causalBuilder site though, once:
1. this pull request in ` vtoure / converter-causal-formats`  gets accepted: https://github.com/vtoure/converter-causal-formats/pull/6 ,
2. followed by an `npm publish` also in `converter-causal-formats`.

**Comment by vtoure** [comment]
That's great! Thank you @stcruy.
